---
Name: mailblockconfig
After:
  - '#emailconfig'
---
SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - MailblockSiteConfig
SilverStripe\SiteConfig\SiteConfigLeftAndMain:
  extensions:
    - MailblockSiteConfigLeftAndMain
SilverStripe\Control\Email\SwiftMailer:
  swift_plugins: 
    - Mailblock\Email\MailblockPlugin
